# Generated by Django 3.2.4 on 2021-06-12 09:16

import datetime
from django.db import migrations, models
import froala_editor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogcategory',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('blog_category', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Blogpost',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('post_title', models.CharField(max_length=50)),
                ('post_slug', models.SlugField(blank=True)),
                ('post_body', froala_editor.fields.FroalaField()),
                ('pub_date', models.DateField(default=datetime.datetime.now)),
                ('thumbnail', models.ImageField(blank=True, default='', upload_to='images/')),
                ('is_active', models.BooleanField(default=True)),
                ('post_category', models.ManyToManyField(blank=True, to='blog.Blogcategory')),
            ],
        ),
    ]
