# Generated by Django 3.2.4 on 2021-06-12 09:16

from django.db import migrations, models
import django.db.models.deletion
import froala_editor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('heading', models.CharField(max_length=100)),
                ('about_thumbnail', models.ImageField(blank=True, upload_to='images/')),
                ('short_description', models.TextField(blank=True)),
                ('description', froala_editor.fields.FroalaField()),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('email_id', models.EmailField(blank=True, max_length=100, null=True)),
                ('social_facebook', models.URLField(blank=True, max_length=500, null=True)),
                ('social_twitter', models.URLField(blank=True, max_length=500, null=True)),
                ('social_youtube', models.URLField(blank=True, max_length=500, null=True)),
                ('social_instagram', models.URLField(blank=True, max_length=500, null=True)),
                ('wikipedia', models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=100)),
                ('category_thumbnail', models.ImageField(blank=True, upload_to='images/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email_id', models.EmailField(max_length=100)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event_poster', models.ImageField(blank=True, upload_to='images/')),
                ('event_heading', models.CharField(blank=True, max_length=200)),
                ('event_description', models.TextField(blank=True, max_length=1000)),
                ('event_venue', models.CharField(blank=True, max_length=150)),
                ('event_date', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, help_text='Please use the following format: <em>YYYY-MM-DD</em>.')),
                ('heading', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Press',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('news', 'news'), ('editorials', 'editorials'), ('interviews', 'interviews'), ('critics', 'critics'), ('press releases', 'press releases')], max_length=100)),
                ('video_caption', models.CharField(blank=True, max_length=100)),
                ('video_thumbnail', models.ImageField(blank=True, upload_to='images/')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('video_code', models.CharField(blank=True, help_text='Enter only video code of youtube video', max_length=100, null=True)),
                ('press_heading', models.CharField(blank=True, max_length=300, null=True)),
                ('press_description', models.TextField(blank=True, max_length=1000)),
                ('created_at', models.DateField(help_text='Please use the following format: <em>YYYY-MM-DD</em>.')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('video_caption', models.CharField(max_length=100)),
                ('video_thumbnail', models.ImageField(blank=True, upload_to='images/')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('video_code', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='images/')),
                ('img_caption', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='index.category')),
            ],
        ),
    ]
