# Generated by Django 3.1.7 on 2021-06-03 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='press',
            name='video_caption',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
