# Generated by Django 3.1.7 on 2021-05-16 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='about_thumbnail',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='category',
            name='category_thumbnail',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
