# Generated by Django 3.1.7 on 2021-06-03 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20210603_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='wikipedia',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
