# Generated by Django 3.1.7 on 2021-05-17 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_video_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_thumbnail',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
