# Generated by Django 3.1.7 on 2021-05-17 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_video_video_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='video_url',
        ),
        migrations.AddField(
            model_name='video',
            name='video_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
