# Generated by Django 3.1.7 on 2021-05-17 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_auto_20210517_1837'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='caption',
            new_name='video_caption',
        ),
    ]
